# Generated by Django 5.1.3 on 2024-11-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthmetric',
            options={'ordering': ['-date']},
        ),
    ]
