# Generated by Django 5.1.3 on 2024-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_healthmetric_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthmetric',
            options={},
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='vitamins',
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='medication_dose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='medication_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='vitamin_dose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='vitamin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='activity_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
