# Generated by Django 5.1.3 on 2024-11-20 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_activitymetric_calories_activitymetric_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationmetric',
            name='is_vitamin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationmetric',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('time_taken', models.TimeField(blank=True, null=True)),
                ('dose_taken', models.CharField(max_length=100)),
                ('was_taken', models.BooleanField(default=False)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.medicationmetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('time_taken', models.TimeField(blank=True, null=True)),
                ('dose_taken', models.CharField(max_length=100)),
                ('was_taken', models.BooleanField(default=False)),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.medicationmetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
