# Generated by Django 5.1.3 on 2024-11-20 20:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_medicationmetric_is_vitamin_medicationmetric_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationmetric',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supplementintake',
            name='supplement',
        ),
        migrations.RemoveField(
            model_name='supplementintake',
            name='user',
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('time_of_day', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdherence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherence_taken', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medication_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.medicationschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicationIntake',
        ),
        migrations.DeleteModel(
            name='MedicationMetric',
        ),
        migrations.DeleteModel(
            name='SupplementIntake',
        ),
    ]
