# Generated by Django 5.1.3 on 2024-11-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_medicationmetric_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationadherence',
            name='adherence_taken',
        ),
        migrations.AddField(
            model_name='medicationadherence',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicationadherence',
            name='date',
            field=models.DateField(),
        ),
    ]
