# Generated by Django 5.1.3 on 2024-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_medicationadherence_adherence_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='dosage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='medication_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='time_of_day',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
