# Generated by Django 5.1.3 on 2024-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_remove_profile_bio_profile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationschedule',
            name='dosage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='medication_name',
            field=models.CharField(max_length=100),
        ),
    ]
