# Generated by Django 5.1.3 on 2024-11-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_medicationschedule_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationschedule',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='time_of_day',
            field=models.CharField(max_length=50),
        ),
    ]
